filetype plugin indent on
set encoding=utf8
set fileformat=unix
set hidden
set wildmenu
set showcmd
set ignorecase
set smartcase
set incsearch
set nostartofline
set number
set relativenumber
set textwidth=79
set colorcolumn=+1
set nowrap
set ruler
set showmatch
set expandtab
set autowrite
set autoread
set noswapfile 
set foldmethod=syntax
set foldlevel=1
set foldnestmax=1
set list
set timeoutlen=1000
set ttimeoutlen=100
set t_Co=256
syntax on
set bg=dark
colo gruvbox
