set nocompatible
filetype plugin indent on
set encoding=utf8
set fileformat=unix
set hidden
set wildmenu
set showcmd
set ignorecase
set smartcase
set incsearch
set expandtab
set nostartofline
set number
set textwidth=80
set colorcolumn=+1
set nowrap
set cursorline
set ruler
set showmatch
set autoindent
set cindent
set autowrite
set autoread
set noswapfile 
set foldmethod=syntax
set foldlevel=1
set foldnestmax=1
syntax on
set background=dark
set t_Co=256
colorscheme gruvbox
